/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mgv;

import java.io.File;
import sm.sound.SMSoundPlayerRecorder;

/**
 * Graba y guarda un audio
 * @author miguelangel
 */
public class VentanaInternaGrabador extends javax.swing.JInternalFrame {
    //Variable que contendrá el medio
    SMSoundPlayerRecorder player;
    /**
     * Constructor VentanaInternaGrabador
     * @param f Fichero donde se grabará el audio
     */
    public VentanaInternaGrabador(File f) {
        initComponents();
        player = new SMSoundPlayerRecorder(f);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton_Grabar_Parar = new javax.swing.JToggleButton();

        setClosable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jToggleButton_Grabar_Parar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mgv/iconos/RecordPressed_48x48.png"))); // NOI18N
        jToggleButton_Grabar_Parar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_Grabar_PararActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToggleButton_Grabar_Parar)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToggleButton_Grabar_Parar)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Botón de dos posiciones:
     *  ---Si presionado: Cambia el icono a stop y comienza a grabar
     *  ---No presionado: Cambia el icono a play y para de grabar
     * @param evt 
     */
    private void jToggleButton_Grabar_PararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_Grabar_PararActionPerformed
        if(jToggleButton_Grabar_Parar.isSelected()){
            jToggleButton_Grabar_Parar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mgv/iconos/StopNormalRed_48x48.png")));
            if(player!=null) player.record();
        }
        else{
            jToggleButton_Grabar_Parar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mgv/iconos/RecordPressed_48x48.png")));
            if(player!=null) player.stop();
        }
    }//GEN-LAST:event_jToggleButton_Grabar_PararActionPerformed

    /**
     * Evento que controla el cierre de la ventana
     * @param evt 
     */
    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        if(player!=null) player.stop();
    }//GEN-LAST:event_formInternalFrameClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton jToggleButton_Grabar_Parar;
    // End of variables declaration//GEN-END:variables
}
